FROM python:3.11-slim

WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code and models directory
COPY src/ /app/src/
COPY models/ /app/models/

EXPOSE 8000

CMD ["python3", "-m", "uvicorn", "src.predict:app", "--host", "0.0.0.0", "--port", "8000"]
